# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.213
neo_version_range=[21,)

loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_id=integratedmanager
mod_name=IntegratedManager
mod_license=MIT
mod_version=1.0.7
mod_group_id=com.davenonymous
mod_authors=Davenonymous
mod_description=A simple viewer mod to get an overview of your Integrated Dynamics networks.

jei_version=19.25.0.324

cyclopscore_version=1.27.1-835
commoncapabilities_version=2.10.1-275

integrateddynamics_version=1.28.1-1340
integratedtunnels_version=1.9.0-488
integratedterminals_version=1.6.17-617
integratedcrafting_version=1.3.2-376
integratedscripting_version=1.0.19-289
integratedrest_version=1.1.15-163
